// Package complete renders the shell completion scripts that xuz emits with
// "xuz completions <shell>".
//
// For the name the binary is known by, the scripts complete:
//   - the flags (-f, --full, --config, --theme, --dry-run, --version) and
//     the subcommands (run, list, ...),
//   - the alias names from the config as the first argument and after
//     "run" and "show" - so "xuz tf-pl<TAB>" completes to "xuz tf-plan",
//   - the theme names after --theme and file paths after --config.
//
// A script calls the binary by the name it was generated for (the base name
// of the invoked binary) and, when the completions were generated with a
// --config PATH, passes that path along (otherwise the binary's default,
// i.e. $XUZ_CONFIG or ~/.xuz/config.yml, is read). In bash and zsh the
// script also registers the completion for every shell alias that points
// at the binary: the shells do not complete an alias with the completion
// of the command it expands to.
package complete

import "strings"

// Shells are the supported completion dialects, in the order the usage line
// lists them.
var Shells = []string{"bash", "zsh", "fish"}

// Placeholders replaced in every template.
const (
	namePlaceholder = "__NAME__"
	cfgPlaceholder  = "__CFG__"
)

// Script returns the completion script for shell (one of Shells,
// case-insensitive) for the command name name and config path configPath
// ("" for the binary's default), e.g. Script("bash", "xuz", ""). It reports
// false when shell is not supported.
func Script(shell, name, configPath string) (string, bool) {
	var template string
	switch strings.ToLower(shell) {
	case "bash":
		template = bashScript
	case "zsh":
		template = zshScript
	case "fish":
		template = fishScript
	default:
		return "", false
	}
	if name == "" {
		name = "xuz"
	}
	out := strings.ReplaceAll(template, namePlaceholder, name)
	out = strings.ReplaceAll(out, cfgPlaceholder, configArgs(configPath))
	return out, true
}

// configArgs renders the --config argument ("" when configPath is empty)
// for embedding in a shell script. It carries a trailing space: the
// placeholder sits right ahead of the subcommand word in the templates.
func configArgs(configPath string) string {
	if configPath == "" {
		return ""
	}
	return "--config " + shellQuote(configPath) + " "
}

// shellQuote wraps s in single quotes for safe embedding in a shell script,
// escaping any embedded single quote.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "'\\''") + "'"
}

// The templates. The first positional argument (and the argument of "run"
// and "show") completes the subcommands and the alias names; a dash word
// completes the flags; --theme completes the theme names and --config the
// file paths. The alias names are read from the config on every completion
// ("__NAME__ __CFG__ls --names"), so new aliases need no regeneration.
const bashScript = `# xuz bash completion - generated by "xuz completions bash".
#
# Completes the flags, the subcommands and the alias names from your config:
# the first argument ("__NAME__ tf-pl<TAB>" -> "__NAME__ tf-plan"), the
# argument of "run" and "show", the theme names after --theme and file paths
# after --config.
_xuz() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"

  local subs="run list ls themes init show completions help"
  local fl="-f --full --config --theme --dry-run --version"

  # A dash word: the flags.
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "$fl" -- "$cur") )
    return 0
  fi

  # Which positional argument is being completed (flags and flag values
  # don't count)?
  local pos=0 first="" skip=0 i w
  for ((i = 1; i < COMP_CWORD; i++)); do
    w="${COMP_WORDS[i]}"
    if [[ "$skip" -eq 1 ]]; then
      skip=0
      continue
    fi
    case "$w" in
      --config|--theme) skip=1 ;;
      -*) ;;
      *)
        [[ -n "$first" ]] || first=$w
        pos=$((pos + 1))
        ;;
    esac
  done

  case "$prev" in
    --config)
      COMPREPLY=( $(compgen -f -- "$cur") )
      return 0
      ;;
    --theme)
      COMPREPLY=( $(compgen -W "$(__NAME__ __CFG__themes 2>/dev/null | awk '{print $1}')" -- "$cur") )
      return 0
      ;;
    run|show)
      COMPREPLY=( $(compgen -W "$(__NAME__ __CFG__ls --names 2>/dev/null)" -- "$cur") )
      return 0
      ;;
    completions)
      COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") )
      return 0
      ;;
    list|ls|themes|init|help)
      return 0
      ;;
  esac

  if [[ "$pos" -eq 0 ]]; then
    # The first positional argument: subcommands and alias names.
    local names
    names=$(__NAME__ __CFG__ls --names 2>/dev/null)
    COMPREPLY=( $(compgen -W "$subs $names" -- "$cur") )
  elif [[ "$pos" -eq 1 && ( "$first" == run || "$first" == show ) ]]; then
    # The alias after "run" or "show", flags in between included.
    local names
    names=$(__NAME__ __CFG__ls --names 2>/dev/null)
    COMPREPLY=( $(compgen -W "$names" -- "$cur") )
  fi
}
complete -F _xuz "__NAME__"
# The shell doesn't complete a shell alias with the completion of the
# command it expands to, so register the completion for every alias that
# runs the binary (e.g. alias xz=xuz). Put this script after your alias
# definitions.
while IFS= read -r _xuz_line; do
  case "$_xuz_line" in
    alias\ *) _xuz_line=${_xuz_line#alias } ;;
    *) continue ;;
  esac
  _xuz_name=${_xuz_line%%=*}
  _xuz_target=${_xuz_line#*=}
  _xuz_target=${_xuz_target#\"}; _xuz_target=${_xuz_target%\"}
  _xuz_target=${_xuz_target#\'}; _xuz_target=${_xuz_target%\'}
  read -r _xuz_first _xuz_rest <<< "$_xuz_target"
  if [[ "$_xuz_first" == "__NAME__" || "$_xuz_first" == xuz ]]; then
    complete -F _xuz "$_xuz_name"
  fi
done <<< "$(alias 2>/dev/null)"
unset _xuz_line _xuz_name _xuz_target _xuz_first _xuz_rest
`

const zshScript = `# xuz zsh completion - generated by "xuz completions zsh".
#
# Completes the flags, the subcommands and the alias names from your config:
# the first argument ("__NAME__ tf-pl<TAB>" -> "__NAME__ tf-plan"), the
# argument of "run" and "show", the theme names after --theme and file paths
# after --config.
_xuz() {
  local -a subs fl
  subs=(run list ls themes init show completions help)
  fl=(-f --full --config --theme --dry-run --version)

  local cur=${words[-1]}
  local prev=${words[-2]}

  # A dash word: the flags.
  if [[ $cur == -* ]]; then
    compadd -a fl
    return
  fi

  # Which positional argument is being completed (flags and flag values
  # don't count)?
  local pos=0 first="" skip=0 i w
  for ((i = 2; i < ${#words}; i++)); do
    w=${words[i]}
    if ((skip)); then
      skip=0
      continue
    fi
    case $w in
      --config|--theme) skip=1 ;;
      -*) ;;
      *)
        [[ -n $first ]] || first=$w
        ((pos++))
        ;;
    esac
  done

  case $prev in
    --config)
      _files
      return
      ;;
    --theme)
      local -a themes
      themes=(${(f)"$(__NAME__ __CFG__themes 2>/dev/null | awk '{print $1}')"})
      compadd -a themes
      return
      ;;
    run|show)
      local -a names
      names=(${(f)"$(__NAME__ __CFG__ls --names 2>/dev/null)"})
      compadd -a names
      return
      ;;
    completions)
      compadd bash zsh fish
      return
      ;;
    list|ls|themes|init|help)
      return
      ;;
  esac

  if ((pos == 0)); then
    # The first positional argument: subcommands and alias names.
    local -a names
    names=(${(f)"$(__NAME__ __CFG__ls --names 2>/dev/null)"})
    compadd -a subs -a names
  elif ((pos == 1)) && [[ $first == run || $first == show ]]; then
    # The alias after "run" or "show", flags in between included.
    local -a names
    names=(${(f)"$(__NAME__ __CFG__ls --names 2>/dev/null)"})
    compadd -a names
  fi
}
compdef _xuz "__NAME__"
# The shell doesn't complete a shell alias with the completion of the
# command it expands to, so register the completion for every alias that
# runs the binary (e.g. alias xz=xuz). Put this script after your alias
# definitions.
_xuz_register_aliases() {
  local -a lines
  local line name target first
  lines=(${(f)"$(alias 2>/dev/null)"})
  for line in $lines; do
    [[ $line == alias\ * ]] || continue
    line=${line#alias }
    name=${line%%=*}
    target=${line#*=}
    target=${target#\"}; target=${target%\"}
    target=${target#\'}; target=${target%\'}
    first=${target%% *}
    if [[ $first == "__NAME__" || $first == xuz ]]; then
      compdef _xuz "$name"
    fi
  done
}
_xuz_register_aliases
`

const fishScript = `# xuz fish completion - generated by "xuz completions fish".
#
# Completes the flags, the subcommands and the alias names from your config:
# the first argument ("__NAME__ tf-pl<TAB>" -> "__NAME__ tf-plan"), the
# argument of "run" and "show", the theme names after --theme and file paths
# after --config.
function _xuz_aliases
  __NAME__ __CFG__ls --names 2>/dev/null
end

function _xuz_themes
  __NAME__ __CFG__themes 2>/dev/null | awk '{print $1}'
end

function _xuz_first_arg
  # the subcommands, then the alias names
  printf '%s\n' run list ls themes init show completions help
  _xuz_aliases
end

complete -c __NAME__ -n "__fish_is_first_arg" -a "(_xuz_first_arg)" -d "alias or subcommand"
complete -c __NAME__ -n "__fish_seen_subcommand_from run show" -a "(_xuz_aliases)" -d "alias"
complete -c __NAME__ -n "__fish_seen_subcommand_from completions" -a "bash zsh fish" -d "shell"
complete -c __NAME__ -l config -r -d 'config file (default $XUZ_CONFIG or ~/.xuz/config.yml)'
complete -c __NAME__ -l theme -r -a "(_xuz_themes)" -d "override theme"
complete -c __NAME__ -s f -l full -d "full-screen mode (default is the short mode)"
complete -c __NAME__ -l dry-run -d "print the resolved command instead of running it"
complete -c __NAME__ -l version -d "print version"
`
